//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobSkills = new HashSet<JobSkill>();
            this.JobStatus = new HashSet<JobStatu>();
        }
    
        public int JobID { get; set; }
        public string JobTitle { get; set; }
        public string JobType { get; set; }
        public string JobSalary { get; set; }
        public string RecruitmentQuota { get; set; }
        public string Location { get; set; }
        public string ExpInYears { get; set; }
        public string JobRequirement { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string JobBenefit { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSkill> JobSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobStatu> JobStatus { get; set; }
    }
}
