//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalProject
    {
        public int PersonalProjectID { get; set; }
        public string ProjectName { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string ShortDescription { get; set; }
        public string ProjectURL { get; set; }
        public Nullable<int> ApplicantID { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
